### ISSUE TITLE
Allow columns to be sized in MainTable

### ISSUE THREAD

**Issue by slimjim777** [canonical-web-and-design/react-components#125]
Currently it appears as though all the columns are the same width. It would be helpful to allow columns to be sized so that some are bigger or smaller than they would be by default.

**Comment by huwshimi** [comment]
Hi @slimjim777. At the moment there's no formal way of setting the column widths, but this is something the Vanilla team have been discussing.

The way we currently do it is by passing a class to the table and setting the column widths via css.

This is an example take from MAAS:

```jsx
<MainTable
      className="dhcp-list"
      ... />
```


```scss
.dhcp-list td,
  .dhcp-list th {
    // Snippet name:
    &:nth-child(1) {
      flex: 0.2 0 0;
    }

    // Type
    &:nth-child(2) {
      flex: 0.08 0 0;
    }

    // Applies to
    &:nth-child(3) {
      flex: 0.12 0 0;
    }

    ...
  }
```

You could also pass specific classes to the columns and headers if you prefer.

Something like this:

```jsx
<MainTable
    headers={[{ content: ..., className: "name-col" }, ...]}
    rows={[{
      columns: [{
          children: ...,
          className: "name-col",
        }],
    }, ...]}
    ... />
```

And then in your CSS you could do:

```css
.name-col {
    flex: 0.2 0 0;
}
```

Hope that helps!
